<a href="https://colab.research.google.com/github/michaellozano/AI_ML_training/blob/main/4_7_Common_MathStat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[10,100,1000],[64,32,16]])

In [ ]:
arr

array([[   1,    2,    3],
       [  10,  100, 1000],
       [  64,   32,   16]])

In [ ]:
np.amin(arr)

1

In [ ]:
np.amin(arr,axis=0)

array([1, 2, 3])

In [ ]:
np.amin(arr,axis=1)

array([ 1, 10, 16])

In [ ]:
np.max(arr)

1000

In [ ]:
np.amax(arr,axis=0)

array([  64,  100, 1000])

In [ ]:
np.amax(arr,axis=1)

array([   3, 1000,   64])

In [ ]:
np.median(arr)

16.0

In [ ]:
np.mean(arr)

136.44444444444446

In [ ]:
np.std(arr)

306.9448416287023

In [ ]:
np.var(arr)

94215.13580246913

In [ ]:
np.percentile(arr,95)

639.9999999999997

In [ ]:
np.floor(arr)

array([[   1.,    2.,    3.],
       [  10.,  100., 1000.],
       [  64.,   32.,   16.]])

In [ ]:
np.ceil(arr)

array([[   1.,    2.,    3.],
       [  10.,  100., 1000.],
       [  64.,   32.,   16.]])

In [ ]:
arr1 = np.array([0.1,0.8,2.2,-2.2,-9.87])

In [ ]:
np.floor(arr1)

array([  0.,   0.,   2.,  -3., -10.])

In [ ]:
np.ceil(arr1)

array([ 1.,  1.,  3., -2., -9.])