<a href="https://colab.research.google.com/github/michaellozano/AI_ML_training/blob/main/4_8_9_indexslicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,5,6])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
arr_1d[0]

1

In [ ]:
arr_1d[-4]

3

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d[0,0]

1

In [ ]:
arr_2d[0,2]

3

In [ ]:
arr_2d[1,-1]

6

In [ ]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr_3d[0,1,2]

6

In [ ]:
#Slicing
arr_1d

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr_1d[1:]

array([2, 3, 4, 5, 6])

In [ ]:
arr_1d[-3:-1]

array([4, 5])

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d[1,1:]

array([5, 6])

In [ ]:
arr_2d[-2:-3:-1]

array([[1, 2, 3]])

In [ ]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr_3d[0,1:,1:]

array([[5, 6]])